Update main.yml
Try bash check

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -4,20 +4,21 @@ on:
     - master
 
 jobs:
-  control-changed-files:
-    name: control changed files
+  check_package_files:
     runs-on: ubuntu-latest
+
     steps:
-      - uses: actions/checkout@v2
-        with:
-          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.
+    - name: Checkout code
+      uses: actions/checkout@v2
 
-      - name: Get changed files
-        id: changed-files
-        uses: tj-actions/changed-files@v14.6
-
-      - name: Check changed files
-        uses: veceluxa/action-control-changes@v1.2
-        with:
-          changed-files: ${{steps.changed-files.outputs.all_modified_files}}
-          nesting: 4
+    - name: Check package files
+      run: |
+        PATTERN3="\/package\/[^\/]+\/[^\/]+\/[^\/]+\/"
+        PATTERN4="\/package\/[^\/]+\/[^\/]+\/[^\/]+\/[^\/]+\/"
+        FILES=$(git diff --name-only ${{ github.base_ref }} ${{ github.sha }} | grep -E "$PATTERN4")
+        if [ -z "$FILES" ]; then
+          echo "Error: PR contains files not belonging to the specified package structure"
+          exit 1
+        else
+          echo "All files in PR belong to the specified package structure"
+        fi
